name: Rough Draft
favicon: null
layout_spectrum: 0.7541665404569358
typography_spectrum: 0.13065966102294624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5001210423652083
  lightness: 0.48818974453024566
  saturation: 0.8297735420055687
  rhythmicContrast: 0.5772126142401248
purpose: []
